version: '3.8'

services:
  # Test Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    image: ai-qualifier:test
    container_name: ai-qualifier-app-test
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
      - APP_ENV=test
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.test
    depends_on:
      - database
      - redis
    networks:
      - ai-qualifier-test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Test Database
  database:
    image: postgres:15-alpine
    container_name: ai-qualifier-db-test
    environment:
      POSTGRES_DB: ai_qualifier_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ai-qualifier-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Test Redis
  redis:
    image: redis:7-alpine
    container_name: ai-qualifier-redis-test
    ports:
      - "6379:6379"
    networks:
      - ai-qualifier-test-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_test_data:
    driver: local

networks:
  ai-qualifier-test-network:
    driver: bridge