version: '3.8'

services:
  # Development Application with Hot Reload
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    image: ai-qualifier:dev
    container_name: ai-qualifier-app-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - APP_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - database
      - redis
    networks:
      - ai-qualifier-dev-network

  # PostgreSQL Database for Development
  database:
    image: postgres:15-alpine
    container_name: ai-qualifier-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ai_qualifier_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init-dev-db.sql:/docker-entrypoint-initdb.d/init-dev-db.sql:ro
    ports:
      - "5433:5432"
    networks:
      - ai-qualifier-dev-network

  # Redis for Development
  redis:
    image: redis:7-alpine
    container_name: ai-qualifier-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6380:6379"
    networks:
      - ai-qualifier-dev-network

  # MailHog for Email Testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ai-qualifier-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - ai-qualifier-dev-network

  # Adminer for Database Management
  adminer:
    image: adminer:latest
    container_name: ai-qualifier-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
    networks:
      - ai-qualifier-dev-network

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  ai-qualifier-dev-network:
    driver: bridge