# Prometheus Alert Rules for AI Qualifier

groups:
  - name: ai-qualifier-alerts
    rules:
      # Application Health Alerts
      - alert: ApplicationDown
        expr: up{job="ai-qualifier-app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "AI Qualifier application is down"
          description: "AI Qualifier application has been down for more than 1 minute."

      - alert: HighResponseTime
        expr: http_request_duration_seconds{quantile="0.95"} > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for more than 5 minutes."

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for more than 2 minutes."

      # Database Alerts
      - alert: DatabaseDown
        expr: up{job="postgresql"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL database is down"
          description: "PostgreSQL database has been down for more than 1 minute."

      - alert: DatabaseConnectionsHigh
        expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High database connection usage"
          description: "Database connection usage is {{ $value | humanizePercentage }} for more than 5 minutes."

      - alert: DatabaseSlowQueries
        expr: rate(pg_stat_database_tup_returned[5m]) / rate(pg_stat_database_tup_fetched[5m]) < 0.1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Database queries are slow"
          description: "Database query efficiency is {{ $value | humanizePercentage }} for more than 10 minutes."

      # Redis Alerts
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis cache is down"
          description: "Redis cache has been down for more than 1 minute."

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis memory usage is high"
          description: "Redis memory usage is {{ $value | humanizePercentage }} for more than 5 minutes."

      # System Resource Alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}."

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}."

      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 15
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Disk space is {{ $value | humanizePercentage }} available on {{ $labels.instance }}."

      # Application-specific Alerts
      - alert: HighFailedLogins
        expr: rate(auth_failed_attempts_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High number of failed login attempts"
          description: "{{ $value }} failed login attempts per second for more than 2 minutes."

      - alert: LowQualificationCompletionRate
        expr: rate(qualifications_completed_total[1h]) / rate(qualifications_started_total[1h]) < 0.3
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Low qualification completion rate"
          description: "Qualification completion rate is {{ $value | humanizePercentage }} for the last hour."

      - alert: AIServiceDown
        expr: ai_service_availability < 1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "AI service is unavailable"
          description: "AI service availability is {{ $value | humanizePercentage }}."

      # Business Metrics Alerts
      - alert: LowActiveUsers
        expr: active_users_count < 10
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "Low number of active users"
          description: "Only {{ $value }} active users in the last 30 minutes."

      - alert: HighAssessmentFailureRate
        expr: rate(assessments_failed_total[1h]) / rate(assessments_total[1h]) > 0.5
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "High assessment failure rate"
          description: "Assessment failure rate is {{ $value | humanizePercentage }} for the last hour."