# Grafana datasource configuration

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: Prometheus
          matcherRegex: "request_id=(\\w+)"
          name: RequestID
          url: "/d/request-details?var-request_id=${__value.raw}"
    editable: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: database:5432
    database: ai_qualifier
    user: postgres
    secureJsonData:
      password: ${DATABASE_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    editable: false